#!/bin/bash

function showHelp()
{
    echo "Usage: [sudo] ./stop_server.sh [OPTIONS]"
    echo "Options:"
    echo -e "\t -h , --help \t\t show this help"
    echo -e "\t -v , --version \t\t show version"
    echo ""
}

# start
ROOT_DIR=$(cd "$(dirname $0)" && pwd)
source $ROOT_DIR/init.inc

if [ $? -ne 0 ] ; then echo "Terminating..." >&2; exit 1; fi

if [ $OS_TYPE == "MACOS" ]; then
    ARGS=$($ROOT_DIR/tmp/getopt_long "$@")
else
    ARGS=$(getopt -o vh --long debug,version,help -n 'Start GameBox Cloud Core' -- "$@")
fi

eval set -- "$ARGS"

declare -i DEBUG=1

while true ; do
    case "$1" in
        -v|--version)
            echo $VERSION
            echo ""
            exit 0
            ;;

        -h|--help)
            showHelp;
            echo ""
            exit 0
            ;;

        --) shift; break ;;

        *)
            echo "invalid option. $1"
            exit 1
            ;;
    esac
done

stopMonitor
stopNginx
stopJobWorkers
stopBeanstalkd
stopRedis

echo -e "\033[33mStop GameBox Cloud Core DONE! \033[0m"
echo ""
